### ISSUE TITLE
Small arrow icons don't respect CSS fill changes

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs-shipyard/ipfs-css#42] opened 2020-06-18 18:01 UTC
See https://dl.dropboxusercontent.com/s/4se8lc2atpo36qf/cBPG7IhgSF.mp4 for an example of how this fails within Storybook for Web UI.

To do:
- Fix the arrow SVG
- Push as a minor update

**Comment by rafaelramalho19** [comment] 2020-06-26 16:11
After creating https://ipfs-css-icons.netlify.app/?path=/story/icons--list&knob-Size=60&knob-Fill=rgba(55,26,199,1)&knob-Search=Small it seems that the problem is not in ipfs-css and it's in webui.

Moving this issue there.

**Closed by rafaelramalho19** 2020-06-26 16:11 UTC
Labels: P2, dif/trivial, effort/hours, good first issue, help wanted, kind/bug, status/ready, topic/design-front-end
